apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "springboot-app.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api/actors
        pathType: Prefix
        backend:
          service:
            name: {{ include "springboot-app.fullname" . }}
            port:
              number: 8080
      - path: /actuator/health
        pathType: Prefix
        backend:
          service:
            name: {{ include "springboot-app.fullname" . }}
            port:
              number: 8080