apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sasl-password-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    saslPassword: {{ .Values.kafka.encryptedSaslPassword }}
  template:
    metadata:
      name: sasl-password-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
