spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.keycloak.svc.cluster.local/realms/cinema
  kafka:
    enabled: ${SPRING_KAFKA_ENABLED:false}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    schema.registry.url: ${SCHEMA_REGISTRY_URL}
    security-protocol: SASL_PLAINTEXT
    sasl:
      mechanism: PLAIN
      username: user1
      password: ${KAFKA_SASL_PASSWORD}