# Sealed Secret for MongoDB credentials
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-secret
  namespace: default
spec:
  encryptedData:
    mongodb-uri: AgADonmLGIa/5XZ5Mhy4E3qygIKkMI27WJnwmo7sT2ZaQ3M+NVA01RB8GiQ6QWOCc9tNDP3IzAgDnnLgtJWDMA+G1knTsBaZsR8lQVbGZOfU6ERvKiVBWb0vg9lmxnk4NqlGgC/ARlSCJc7uYZk0Kcb+8+Ak/V0mCJRY5ulzFpSG9yOnoCGNlFLoYOHjxeTyQkQmxTaBkLaKf6P4lRQ3h3wT55NR/shFKNRbd8+Vy6r/np+7KMB5A0Os7ZK8AdvYc99NQsInK0Tn8Sy1BH8LtxEB8G4fRg37N9oAyonxvWLLOrJrmtP441LzfiVTVWW3nSDPata3XReN9+epT4zenfNs1+SfONWmd/qP82nbXjimw4MuOnfDZwyRZx7E/TpiBKRsHGCyGD5fLjM3VoZIm6S1VcI3Z2PTQhUg7fe0C2sMZcqn4NVmqVkhWgsggLXZy6mWrVXN4qFJRsC/H8/vh1PAGEd/oOi4HLcSumRSD7zNaQ4w/ImbFuZD5ZNWssrvGqAR8nu70R9gFBIX+B7g/MTbGxTRyiEtKwS2hH8eiQZb+N+3vQLZN7XNHMgQBkwVbD7M/XRXctP5m1mNTmQ0bes8hFLgjRHP3+Q7UK5RRlWz3hMtVMamD9WJxWhUjfFAlEK5JpAxZxRPfvwzXbs2n5i1ITGZGrUeTztYDWru7LxO9uUwKXvYahVGxSO2arm1b3sTjxmUsSt9Pokg3gHzd8P7hoB14ELc+I5NlNKi5dB0NgKQpHTBi8ZXPv1q8JbxsimSK6TeMs0ieXMnaHSr5zwVrpa3GbXwLXbcg9/u+/NfIw==
  template:
    metadata:
      name: mongodb-secret
      namespace: default
    type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: registry.gitlab.com/cinema7590904/service-actor-management:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-uri
          resources:
            requests:
              ephemeral-storage: "1Gi"
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
